import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Theme-aware colors via CSS variables (dark default, light via data-theme)
        bg: "var(--bg)",
        "bg-2": "var(--bg-2)",
        "bg-3": "var(--bg-3)",
        panel: "var(--panel)",
        "panel-2": "var(--panel-2)",
        hover: "var(--hover)",
        border: "var(--border)",
        "border-2": "var(--border-2)",
        "border-3": "var(--border-3)",
        text: "var(--text)",
        "text-2": "var(--text-2)",
        "text-3": "var(--text-3)",
        "text-4": "var(--text-4)",
        accent: "var(--accent)",
        "accent-2": "var(--accent-2)",
        "accent-glow": "var(--accent-glow)",
        "accent-wash": "var(--accent-wash)",
        success: "var(--success)",
        "success-wash": "var(--success-wash)",
        warning: "var(--warning)",
        "warning-wash": "var(--warning-wash)",
        danger: "var(--danger)",
        "danger-wash": "var(--danger-wash)",
        info: "var(--info)",
        "info-wash": "var(--info-wash)",
        // product brand colors (used in dots + chips)
        "p-bee": "#F5B84A",
        "p-high": "#4ADE80",
        "p-axe": "#A78BFA",
        "p-bloom": "#F472B6",
        // chart palette — same as prototype
        "chart-1": "#7B5CFF",
        "chart-2": "#22D3EE",
        "chart-3": "#F5B84A",
        "chart-4": "#4ADE80",
        "chart-5": "#F472B6",
      },
      fontFamily: {
        sans: ['"Poppins"', "ui-sans-serif", "system-ui"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      fontSize: {
        "micro": ["11px", { lineHeight: "1.45", fontWeight: "500" }],
        "caption": ["12px", { lineHeight: "1.5", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "1.55", fontWeight: "400" }],
        "body": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "subhead": ["15px", { lineHeight: "1.35", fontWeight: "600", letterSpacing: "-0.01em" }],
        "heading": ["17px", { lineHeight: "1.3", fontWeight: "600", letterSpacing: "-0.015em" }],
        "title": ["22px", { lineHeight: "1.2", fontWeight: "700", letterSpacing: "-0.02em" }],
        "display": ["28px", { lineHeight: "1.15", fontWeight: "700", letterSpacing: "-0.025em" }],
        "display-lg": ["36px", { lineHeight: "1.1", fontWeight: "700", letterSpacing: "-0.03em" }],
      },
      letterSpacing: {
        "tightest": "-0.03em",
        "tighter": "-0.02em",
        "tight": "-0.01em",
        "normal": "-0.006em",
        "wide": "0.02em",
        "wider": "0.06em",
        "widest": "0.08em",
      },
    },
  },
  plugins: [],
} satisfies Config;
