/**
 * Apply pending migrations from ./drizzle/ to the database at DATABASE_URL.
 *
 *   Local dev:  pnpm db:migrate
 *   Prod:       pnpm --filter @tu/db migrate  (run as a one-shot job on deploy)
 *
 * Migration SQL files are generated by `drizzle-kit generate` from schema.ts
 * and committed under packages/db/drizzle/. Re-running is safe (drizzle tracks
 * applied migrations in the `__drizzle_migrations` table).
 */
import { config } from "dotenv";
config({ path: "../../.env" });

import { drizzle } from "drizzle-orm/postgres-js";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

async function main() {
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not set. Copy .env.example to .env.");
  }

  console.log("→ running migrations…");
  const client = postgres(process.env.DATABASE_URL, { max: 1, prepare: false });
  const db = drizzle(client);

  const start = Date.now();
  await migrate(db, { migrationsFolder: "./drizzle" });
  console.log(`✓ migrations complete in ${Date.now() - start}ms`);

  await client.end({ timeout: 5 });
}

main().catch((e) => {
  console.error("migration failed:", e);
  process.exit(1);
});
